#!/bin/env bash

# save the cwd  
cwd=$(pwd)

# change to the directory of the script
cd $(dirname $0)

source ~/.bashrc

tclo verser.mjs processFiles.mjs jsconfig.json eslint.config.js translation.mjs lib 

# restore the cwd
cd $cwd